"""Reproducible synthetic behavior fixture; NOT independent scientific validation."""
from pathlib import Path
import argparse
import hashlib
import json
import math
import sys
from start_app import choose_python
import subprocess

ROOT = Path(__file__).resolve().parents[1]

def main():
    python = choose_python(False)
    if Path(sys.executable).resolve() != python.resolve():
        return subprocess.call([str(python), str(Path(__file__).resolve()), *sys.argv[1:]])
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, required=True)
    out = parser.parse_args().output.resolve()
    out.mkdir(parents=True, exist_ok=True)
    sys.path.insert(0, str(ROOT / 'assets/app'))
    from app.services.agent_tools import invoke_tool
    files = []
    energies = [238.632,295.224,351.932,583.187,609.312,911.204,1460.822]
    for name, scale, live in [('standard',1.,True), ('sample',.5,True), ('missing-live',.5,False)]:
        rows = ['DATE=2025-01-25', 'TIME=00:00:00'] + (['TLIVE=10000'] if live else [])
        for channel in range(8192):
            count = 18. + sum((24000+i*1800)*scale/(math.sqrt(2*math.pi)*3)*math.exp(-.5*((channel-(energy-.1)/.2)/3)**2) for i,energy in enumerate(energies))
            rows.append(f'{channel}\t{count:.8f}')
        path = out / (name+'.txt')
        path.write_text('\n'.join(rows), encoding='utf8')
        files.append({'path':path.name,'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
    manifest = {'source_class':'synthetic_behavior_only','license':'MIT, generated by project code',
                'calibration_basis':'fixed generator E=0.2*CH+0.1, not fitted to sample identity','files':files}
    (out/'fixture_manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf8')
    request = {'calibration':{'path':str(out/'standard.txt')}, 'samples':[{'path':str(out/'sample.txt'),'mass_g':500}],
        'settings':{'source_kind':'custom','calibration_mass_g':337.76,'reference_date':'2015-01-25',
            'reference_activities_bq':{'Ra226':903,'Th232':483,'K40':668},
            'standard_certificate_id':'SYNTHETIC-NOT-A-REAL-CERTIFICATE','standard_traceable':True,
            'geometry_match':True,'matrix_match':True,'assume_chain_equilibrium':True},
        'calibration_specs':{'calibration':{'slope':.2,'intercept':.1},'sample':{'slope':.2,'intercept':.1}}}
    records = []
    for name in ['normal','missing-source-values','missing-live']:
        case = json.loads(json.dumps(request))
        if name == 'missing-source-values': case['settings'] = {'source_kind':'custom'}
        if name == 'missing-live': case['samples'][0]['path'] = str(out/'missing-live.txt')
        (out/(name+'-request.json')).write_text(json.dumps(case,indent=2),encoding='utf8')
        preflight = invoke_tool('validate_inputs',case)
        result = invoke_tool('analyze_ra_th_k',case)
        expected = 'ready_for_quantification' if name == 'normal' else 'blocked'
        assert preflight['data']['workflow_status'] == expected, preflight
        assert result['data']['quality']['workflow_status'] == expected if name == 'normal' else result['error_code'] == 'blocked_quality_gate'
        (out/(name+'-result.json')).write_text(json.dumps(result,indent=2),encoding='utf8')
        records.append({'case':name,'expected':expected,'actual':preflight['data']['workflow_status']})
        if name == 'normal':
            assert invoke_tool('validate_analysis',{'analysis':result['data']})['status']=='ok'
            for language in ['zh','zht','en','fr']:
                for fmt in ['pdf','png','xlsx']:
                    exported=invoke_tool('export_report',{'analysis':result['data'],'format':fmt,'language':language,
                        'output_directory':str(out),'filename_stem':f'normal-{language}','overwrite':True})
                    assert exported['status']=='ok',exported
    (out/'behavior_results.json').write_text(json.dumps({'evidence_class':'deterministic synthetic tool behavior, NOT real host effect',
        'cases':records},indent=2),encoding='utf8')
    print(json.dumps({'status':'passed','cases':records,'output':str(out)},ensure_ascii=False))
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
